{% set data= load_setup_py_data() %}
package:
    name: "ts-environment"
    version: {{ data.get('version') }}

source:
    path: ../

build:
    script: python -m pip install --no-deps --ignore-installed .
    script_env:
        - PATH
        - PYTHONPATH
        - LD_LIBRARY_PATH
        - OSPL_HOME
        - PYTHON_BUILD_VERSION
        - PYTHON_BUILD_LOCATION
        - LSST_DDS_DOMAIN
        - TS_CONFIG_OCS_DIR

test:
    requires:
        - pytest
        - pytest-flake8
        - pytest-cov
        - asynctest
        - numpy
        - astropy
        - jsonschema
        - pyyaml
        - boto3
        - moto
        - ts-dds
        - ts-idl {{ idl_version }}
        - ts-salobj {{ salobj_version }}
        - black == 19.10b0
    source_files:
        - python
        - bin
        - tests
        - schema
        - setup.cfg
    commands:
        - py.test

requirements:
    host:
        - python
        - pip
        - setuptools_scm
        - setuptools
        - pytest-runner
    run:
        - python
        - setuptools
        - setuptools_scm
        - ts-salobj
        - ts-idl
